from ophyd.controls.areadetector.detectors import (AreaDetector, ADSignal)


class Xspress3Detector(AreaDetector):
    _html_docs = ['']

    xs_config_path = ADSignal('CONFIG_PATH', has_rbv=True)
    xs_config_save_path = ADSignal('CONFIG_SAVE_PATH', has_rbv=True)
    xs_connect = ADSignal('CONNECT')
    xs_connected = ADSignal('CONNECTED')
    xs_ctrl_dtc = ADSignal('CTRL_DTC', has_rbv=True)
    xs_ctrl_mca_roi = ADSignal('CTRL_MCA_ROI', has_rbv=True)
    xs_debounce = ADSignal('DEBOUNCE', has_rbv=True)
    xs_disconnect = ADSignal('DISCONNECT')
    xs_erase = ADSignal('ERASE')
    xs_erase_array_counters = ADSignal('ERASE_ArrayCounters')
    xs_erase_attr_reset = ADSignal('ERASE_AttrReset')
    xs_erase_proc_reset_filter = ADSignal('ERASE_PROC_ResetFilter')
    xs_frame_count = ADSignal('FRAME_COUNT_RBV', rw=False)
    xs_hdf_capture = ADSignal('HDF5:Capture_RBV', rw=False)
    xs_hdf_num_capture_calc = ADSignal('HDF5:NumCapture_CALC')
    xs_invert_f0 = ADSignal('INVERT_F0', has_rbv=True)
    xs_invert_veto = ADSignal('INVERT_VETO', has_rbv=True)
    xs_max_frames = ADSignal('MAX_FRAMES_RBV', rw=False)
    xs_max_frames_driver = ADSignal('MAX_FRAMES_DRIVER_RBV', rw=False)
    xs_max_num_channels = ADSignal('MAX_NUM_CHANNELS_RBV', rw=False)
    xs_max_spectra = ADSignal('MAX_SPECTRA', has_rbv=True)
    xs_name = ADSignal('NAME')
    xs_num_cards = ADSignal('NUM_CARDS_RBV', rw=False)
    xs_num_channels = ADSignal('NUM_CHANNELS', has_rbv=True)
    xs_num_frames_config = ADSignal('NUM_FRAMES_CONFIG', has_rbv=True)
    xs_reset = ADSignal('RESET')
    xs_restore_settings = ADSignal('RESTORE_SETTINGS')
    xs_run_flags = ADSignal('RUN_FLAGS', has_rbv=True)
    xs_save_settings = ADSignal('SAVE_SETTINGS')
    xs_trigger = ADSignal('TRIGGER')
    xs_update = ADSignal('UPDATE')
    xs_update_attr = ADSignal('UPDATE_AttrUpdate')
