from ophyd.controls import EpicsMotor, PVPositioner

ssa1_hgap = EpicsMotor('XF:03IDB-OP{Slt:SSA1-Ax:XAp}Mtr', name='ssa1_hgap')
ssa1_vgap = EpicsMotor('XF:03IDB-OP{Slt:SSA1-Ax:YAp}Mtr', name='ssa1_vgap')
ssa1_hcen = EpicsMotor('XF:03IDB-OP{Slt:SSA1-Ax:X}Mtr', name='ssa1_hcen')
ssa1_vcen = EpicsMotor('XF:03IDB-OP{Slt:SSA1-Ax:Y}Mtr', name='ssa1_vcen')
bpm6_y = EpicsMotor('XF:03IDB-OP{BPM:6-Ax:Y}Mtr', name='bpm6_y')

# idb_m1 = EpicsMotor('XF:03IDB-OP{Slt:SSA1-Ax:6}Mtr', name='idb_m1')
# idb_m2 = EpicsMotor('XF:03IDB-OP{Slt:SSA1-Ax:7}Mtr', name='idb_m2')
# idb_m3 = EpicsMotor('XF:03IDB-OP{Slt:SSA1-Ax:8}Mtr', name='idb_m3')

ssa2_hgap = EpicsMotor('XF:03IDC-OP{Slt:SSA2-Ax:XAp}Mtr', name='ssa2_hgap')
ssa2_vgap = EpicsMotor('XF:03IDC-OP{Slt:SSA2-Ax:YAp}Mtr', name='ssa2_vgap')
ssa2_hcen = EpicsMotor('XF:03IDC-OP{Slt:SSA2-Ax:X}Mtr', name='ssa2_hcen')
ssa2_vcen = EpicsMotor('XF:03IDC-OP{Slt:SSA2-Ax:Y}Mtr', name='ssa2_vcen')
s3_top = EpicsMotor('XF:03IDC-OP{Slt:3-Ax:Top}Mtr', name='s3_top')
s3_bot = EpicsMotor('XF:03IDC-OP{Slt:3-Ax:Btm}Mtr', name='s3_bot')
s3_inb = EpicsMotor('XF:03IDC-OP{Slt:3-Ax:Inb}Mtr', name='s3_inb')
s3_outb = EpicsMotor('XF:03IDC-OP{Slt:3-Ax:Outb}Mtr', name='s3_outb')

# mc2_m1 = EpicsMotor('XF:03IDC-ES{MC:2-Ax:1}Mtr', name='mc2_m1')
# mc2_m2 = EpicsMotor('XF:03IDC-ES{MC:2-Ax:2}Mtr', name='mc2_m2')
# mc2_m3 = EpicsMotor('XF:03IDC-ES{MC:2-Ax:3}Mtr', name='mc2_m3')
# mc2_m4 = EpicsMotor('XF:03IDC-ES{MC:2-Ax:4}Mtr', name='mc2_m4')
# mc2_m5 = EpicsMotor('XF:03IDC-ES{MC:2-Ax:5}Mtr', name='mc2_m5')
# mc2_m6 = EpicsMotor('XF:03IDC-ES{MC:2-Ax:6}Mtr', name='mc2_m6')
# mc2_m7 = EpicsMotor('XF:03IDC-ES{MC:2-Ax:7}Mtr', name='mc2_m7')
# mc2_m8 = EpicsMotor('XF:03IDC-ES{MC:2-Ax:8}Mtr', name='mc2_m8')
# mc3_m1 = EpicsMotor('XF:03IDC-ES{MC:3-Ax:1}Mtr', name='mc3_m1')
# mc3_m2 = EpicsMotor('XF:03IDC-ES{MC:3-Ax:2}Mtr', name='mc3_m2')
# mc3_m3 = EpicsMotor('XF:03IDC-ES{MC:3-Ax:3}Mtr', name='mc3_m3')
# mc3_m4 = EpicsMotor('XF:03IDC-ES{MC:3-Ax:4}Mtr', name='mc3_m4')
# mc3_m5 = EpicsMotor('XF:03IDC-ES{MC:3-Ax:5}Mtr', name='mc3_m5')
# mc3_m6 = EpicsMotor('XF:03IDC-ES{MC:3-Ax:6}Mtr', name='mc3_m6')
# mc3_m7 = EpicsMotor('XF:03IDC-ES{MC:3-Ax:7}Mtr', name='mc3_m7')
# mc3_m8 = EpicsMotor('XF:03IDC-ES{MC:3-Ax:8}Mtr', name='mc3_m8')
# mc4_m1 = EpicsMotor('XF:03IDC-ES{MC:4-Ax:1}Mtr', name='mc4_m1')
# mc4_m2 = EpicsMotor('XF:03IDC-ES{MC:4-Ax:2}Mtr', name='mc4_m2')
# mc4_m3 = EpicsMotor('XF:03IDC-ES{MC:4-Ax:3}Mtr', name='mc4_m3')
# mc4_m4 = EpicsMotor('XF:03IDC-ES{MC:4-Ax:4}Mtr', name='mc4_m4')
# mc4_m5 = EpicsMotor('XF:03IDC-ES{MC:4-Ax:5}Mtr', name='mc4_m5')
# mc4_m6 = EpicsMotor('XF:03IDC-ES{MC:4-Ax:6}Mtr', name='mc4_m6')
# mc4_m7 = EpicsMotor('XF:03IDC-ES{MC:4-Ax:7}Mtr', name='mc4_m7')
# mc4_m8 = EpicsMotor('XF:03IDC-ES{MC:4-Ax:8}Mtr', name='mc4_m8')

p_vx = EpicsMotor('XF:03IDC-ES{Proto:1-Ax:1}Mtr', name='p_vx')
p_vy = EpicsMotor('XF:03IDC-ES{Proto:1-Ax:2}Mtr', name='p_vy')
p_vt = EpicsMotor('XF:03IDC-ES{Proto:1-Ax:3}Mtr', name='p_vt')
p_vchi = EpicsMotor('XF:03IDC-ES{Proto:1-Ax:4}Mtr', name='p_vchi')
p_osat = EpicsMotor('XF:03IDC-ES{Proto:1-Ax:5}Mtr', name='p_osat')
p_osay = EpicsMotor('XF:03IDC-ES{Proto:1-Ax:6}Mtr', name='p_osay')
p_osax = EpicsMotor('XF:03IDC-ES{Proto:1-Ax:7}Mtr', name='p_osax')
p_osaz = EpicsMotor('XF:03IDC-ES{Proto:1-Ax:8}Mtr', name='p_osaz')
s4_vgap = EpicsMotor('XF:03IDC-ES{Slt:4-Ax:X}Mtr', name='s4_vgap')
s4_vcen = EpicsMotor('XF:03IDC-ES{Slt:4-Ax:Y}Mtr', name='s4_vcen')
s4_hgap = EpicsMotor('XF:03IDC-ES{Slt:4-Ax:Z}Mtr', name='s4_hgap')
s4_hcen = EpicsMotor('XF:03IDC-ES{Slt:4-Ax:Top}Mtr', name='s4_hcen')

# mc6_m5 = EpicsMotor('XF:03IDC-ES{MC:6-Ax:5}Mtr', name='mc6_m5')
# mc6_m6 = EpicsMotor('XF:03IDC-ES{MC:6-Ax:6}Mtr', name='mc6_m6')
# mc6_m7 = EpicsMotor('XF:03IDC-ES{MC:6-Ax:7}Mtr', name='mc6_m7')

bpm7_y = EpicsMotor('XF:03IDC-ES{BPM:7-Ax:Y}Mtr', name='bpm7_y')

# mc7_m1 = EpicsMotor('XF:03IDC-ES{MC:7-Ax:1}Mtr', name='mc7_m1')
# mc7_m2 = EpicsMotor('XF:03IDC-ES{MC:7-Ax:2}Mtr', name='mc7_m2')
# mc7_m3 = EpicsMotor('XF:03IDC-ES{MC:7-Ax:3}Mtr', name='mc7_m3')
# mc7_m4 = EpicsMotor('XF:03IDC-ES{MC:7-Ax:4}Mtr', name='mc7_m4')
# mc7_m5 = EpicsMotor('XF:03IDC-ES{MC:7-Ax:5}Mtr', name='mc7_m5')
# mc7_m6 = EpicsMotor('XF:03IDC-ES{MC:7-Ax:6}Mtr', name='mc7_m6')
# mc7_m7 = EpicsMotor('XF:03IDC-ES{MC:7-Ax:7}Mtr', name='mc7_m7')
# mc7_m8 = EpicsMotor('XF:03IDC-ES{MC:7-Ax:8}Mtr', name='mc7_m8')

questar_f = EpicsMotor('XF:03IDC-ES{MC:8-Ax:1}Mtr', name='questar_f')

# mc8_m2 = EpicsMotor('XF:03IDC-ES{MC:8-Ax:2}Mtr', name='mc8_m2')
# mc8_m3 = EpicsMotor('XF:03IDC-ES{MC:8-Ax:3}Mtr', name='mc8_m3')
# mc8_m4 = EpicsMotor('XF:03IDC-ES{MC:8-Ax:4}Mtr', name='mc8_m4')
# mc8_m5 = EpicsMotor('XF:03IDC-ES{MC:8-Ax:5}Mtr', name='mc8_m5')
# mc8_m6 = EpicsMotor('XF:03IDC-ES{MC:8-Ax:6}Mtr', name='mc8_m6')
# mc8_m7 = EpicsMotor('XF:03IDC-ES{MC:8-Ax:7}Mtr', name='mc8_m7')
# mc8_m8 = EpicsMotor('XF:03IDC-ES{MC:8-Ax:8}Mtr', name='mc8_m8')
# mc9_m1 = EpicsMotor('XF:03IDC-ES{MC:9-Ax:1}Mtr', name='mc9_m1')
# mc9_m2 = EpicsMotor('XF:03IDC-ES{MC:9-Ax:2}Mtr', name='mc9_m2')
# mc9_m3 = EpicsMotor('XF:03IDC-ES{MC:9-Ax:3}Mtr', name='mc9_m3')
# mc9_m4 = EpicsMotor('XF:03IDC-ES{MC:9-Ax:4}Mtr', name='mc9_m4')

s6_vgap = EpicsMotor('XF:03IDC-ES{Slt:6-Ax:Vgap}Mtr', name='s6_vgap')
s6_vcen = EpicsMotor('XF:03IDC-ES{Slt:6-Ax:Vcen}Mtr', name='s6_vcen')
s6_hgap = EpicsMotor('XF:03IDC-ES{Slt:6-Ax:Hgap}Mtr', name='s6_hgap')
s6_vcen = EpicsMotor('XF:03IDC-ES{Slt:6-Ax:Hcen}Mtr', name='s6_vcen')
s5_hcen = EpicsMotor('XF:03IDC-ES{Slt:5-Ax:Hcen}Mtr', name='s5_hcen')
s5_hgap = EpicsMotor('XF:03IDC-ES{Slt:5-Ax:Hgap}Mtr', name='s5_hgap')
s5_vcen = EpicsMotor('XF:03IDC-ES{Slt:5-Ax:Vcen}Mtr', name='s5_vcen')
s5_vgap = EpicsMotor('XF:03IDC-ES{Slt:5-Ax:Vgap}Mtr', name='s5_vgap')

# mc10_m5 = EpicsMotor('XF:03IDC-ES{MC:10-Ax:5}Mtr', name='mc10_m5')
# mc10_m6 = EpicsMotor('XF:03IDC-ES{MC:10-Ax:6}Mtr', name='mc10_m6')
# mc10_m7 = EpicsMotor('XF:03IDC-ES{MC:10-Ax:7}Mtr', name='mc10_m7')
# mc10_m8 = EpicsMotor('XF:03IDC-ES{MC:10-Ax:8}Mtr', name='mc10_m8')

fdet2_z = EpicsMotor('XF:03IDC-ES{Det:Bruk-Ax:Z}Mtr', name='fdet2_z')
fdet2_y = EpicsMotor('XF:03IDC-ES{Det:Bruk-Ax:Y}Mtr', name='fdet2_y')
fdet2_x = EpicsMotor('XF:03IDC-ES{Det:Bruk-Ax:X}Mtr', name='fdet2_x')
fdet1_z = EpicsMotor('XF:03IDC-ES{Det:Vort-Ax:Z}Mtr', name='fdet1_z')
fdet1_y = EpicsMotor('XF:03IDC-ES{Det:Vort-Ax:Y}Mtr', name='fdet1_y')
fdet1_x = EpicsMotor('XF:03IDC-ES{Det:Vort-Ax:X}Mtr', name='fdet1_x')

# mc11_m7 = EpicsMotor('XF:03IDC-ES{MC:11-Ax:7}Mtr', name='mc11_m7')
# mc11_m8 = EpicsMotor('XF:03IDC-ES{MC:11-Ax:8}Mtr', name='mc11_m8')
# mc12_m1 = EpicsMotor('XF:03IDC-ES{MC:12-Ax:1}Mtr', name='mc12_m1')
# mc12_m2 = EpicsMotor('XF:03IDC-ES{MC:12-Ax:2}Mtr', name='mc12_m2')
# mc12_m3 = EpicsMotor('XF:03IDC-ES{MC:12-Ax:3}Mtr', name='mc12_m3')

bs_x = EpicsMotor('XF:03IDC-ES{MC:12-Ax:4}Mtr', name='bs_x')
bs_y = EpicsMotor('XF:03IDC-ES{MC:12-Ax:5}Mtr', name='bs_y')
# mc12_m6 = EpicsMotor('XF:03IDC-ES{MC:12-Ax:6}Mtr', name='mc12_m6')
# mc12_m7 = EpicsMotor('XF:03IDC-ES{MC:12-Ax:7}Mtr', name='mc12_m7')
# mc12_m8 = EpicsMotor('XF:03IDC-ES{MC:12-Ax:8}Mtr', name='mc12_m8')

diff_z = EpicsMotor('XF:03IDC-ES{Diff-Ax:Z}Mtr', name='diff_z')
diff_x = EpicsMotor('XF:03IDC-ES{Diff-Ax:X}Mtr', name='diff_x')
diff_y1 = EpicsMotor('XF:03IDC-ES{Diff-Ax:Y1}Mtr', name='diff_y1')
diff_y2 = EpicsMotor('XF:03IDC-ES{Diff-Ax:Y2}Mtr', name='diff_y2')
diff_yaw = EpicsMotor('XF:03IDC-ES{Diff-Ax:Yaw}Mtr', name='diff_yaw')
diff_c1 = EpicsMotor('XF:03IDC-ES{Diff-Ax:C1}Mtr', name='diff_c1')
diff_c2 = EpicsMotor('XF:03IDC-ES{Diff-Ax:C2}Mtr', name='diff_c2')
diff_c3 = EpicsMotor('XF:03IDC-ES{Diff-Ax:C3}Mtr', name='diff_c3')

s7_vgap = EpicsMotor('XF:03IDC-ES{Slt:7-Ax:Vgap}Mtr', name='s7_vgap')
s7_vcen = EpicsMotor('XF:03IDC-ES{Slt:7-Ax:Vcen}Mtr', name='s7_vcen')
s7_hgap = EpicsMotor('XF:03IDC-ES{Slt:7-Ax:Hgap}Mtr', name='s7_hgap')
s7_hcen = EpicsMotor('XF:03IDC-ES{Slt:7-Ax:Hcen}Mtr', name='s7_hcen')

# mc14_m5 = EpicsMotor('XF:03IDC-ES{MC:14-Ax:5}Mtr', name='mc14_m5')
# mc14_m6 = EpicsMotor('XF:03IDC-ES{MC:14-Ax:6}Mtr', name='mc14_m6')
# mc14_m7 = EpicsMotor('XF:03IDC-ES{MC:14-Ax:7}Mtr', name='mc14_m7')
# mc14_m8 = EpicsMotor('XF:03IDC-ES{MC:14-Ax:8}Mtr', name='mc14_m8')
